In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

data = {
    'EmployeeID': range(101, 121),
    'Age': [25, 28, 32, 45, 41, 38, np.nan, 29, 34, 36, 40, 22, 27, 30, np.nan, 33, 44, 39, 26, 31],
    'Department': ['IT', 'HR', 'Finance', 'IT', 'Marketing', 'Finance', 'IT', 'HR',
                   'Finance', 'IT', 'Marketing', 'Finance', np.nan, 'HR', 'IT',
                   'Finance', 'IT', 'Marketing', 'HR', np.nan],
    'ExperienceYears': [1, 3, 5, 10, np.nan, 7, 9, 2, 4, np.nan, 12, 1, 6, 3, 5, np.nan, 8, 11, 2, 4],
    'TrainingHours': [15, 20, np.nan, 40, 25, 35, 18, np.nan, 22, 28, 30, 12, 17, 24, 26, 33, np.nan, 29, 21, 23],
    'SkillScore': [70, 76, 80, 90, np.nan, 85, 88, 72, 78, 92, 95, 68, np.nan, 74, 82, 87, 91, np.nan, 77, 79],
    'PerformanceRating': [3, 4, 4, 5, np.nan, 4, 5, 3, np.nan, 5, 5, 2, 3, 4, np.nan, 4, 5, 4, 3, 4]
}

df_lab = pd.DataFrame(data)
df_lab

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating
0,101,25.0,IT,1.0,15.0,70.0,3.0
1,102,28.0,HR,3.0,20.0,76.0,4.0
2,103,32.0,Finance,5.0,NaN,80.0,4.0
3,104,45.0,IT,10.0,40.0,90.0,5.0
4,105,41.0,Marketing,NaN,25.0,NaN,NaN
5,106,38.0,Finance,7.0,35.0,85.0,4.0
6,107,NaN,IT,9.0,18.0,88.0,5.0
7,108,29.0,HR,2.0,NaN,72.0,3.0
8,109,34.0,Finance,4.0,22.0,78.0,NaN
9,110,36.0,IT,NaN,28.0,92.0,5.0
10,111,40.0,Marketing,12.0,30.0,95.0,5.0
11,112,22.0,Finance,1.0,12.0,68.0,2.0
12,113,27.0,NaN,6.0,17.0,NaN,3.0
13,114,30.0,HR,3.0,24.0,74.0,4.0
14,115,NaN,IT,5.0,26.0,82.0,NaN
15,116,33.0,Finance,NaN,33.0,87.0,4.0
16,117,44.0,IT,8.0,NaN,91.0,5.0
17,118,39.0,Marketing,11.0,29.0,NaN,4.0
18,119,26.0,HR,2.0,21.0,77.0,3.0
19,120,31.0,NaN,4.0,23.0,79.0,4.0


### **LAB QUESTIONS (12 Tasks)**

 Participants must use **Pandas** to solve these questions.
They will use the dataset `df_lab`.

---

### Section A: Basic Exploration**

### **1️⃣ Display the first 7 rows and the last 5 rows.**

In [3]:
df_lab.head(7)

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating
0,101,25.0,IT,1.0,15.0,70.0,3.0
1,102,28.0,HR,3.0,20.0,76.0,4.0
2,103,32.0,Finance,5.0,NaN,80.0,4.0
3,104,45.0,IT,10.0,40.0,90.0,5.0
4,105,41.0,Marketing,NaN,25.0,NaN,NaN
5,106,38.0,Finance,7.0,35.0,85.0,4.0
6,107,NaN,IT,9.0,18.0,88.0,5.0

In [4]:
df_lab.tail(5)

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating
15,116,33.0,Finance,NaN,33.0,87.0,4.0
16,117,44.0,IT,8.0,NaN,91.0,5.0
17,118,39.0,Marketing,11.0,29.0,NaN,4.0
18,119,26.0,HR,2.0,21.0,77.0,3.0
19,120,31.0,NaN,4.0,23.0,79.0,4.0



### **2️⃣ Print the summary of all column datatypes and missing values.**

In [5]:
df_lab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         20 non-null     int64
 1   Age                18 non-null     float64
 2   Department         18 non-null     object
 3   ExperienceYears    17 non-null     float64
 4   TrainingHours      17 non-null     float64
 5   SkillScore         17 non-null     float64
 6   PerformanceRating  17 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.2+ KB

In [6]:
df_lab.isnull().sum()

EmployeeID           0
Age                  2
Department           2
ExperienceYears      3
TrainingHours        3
SkillScore           3
PerformanceRating    3
dtype: int64



### **3️⃣ Show descriptive statistics for numerical columns.**

In [7]:
df_lab.describe()

,EmployeeID,Age,ExperienceYears,TrainingHours,SkillScore,PerformanceRating
count,20.00000,18.000000,17.000000,17.000000,17.000000,17.000000
mean,110.50000,33.333333,5.470588,24.588235,81.411765,3.941176
std,5.91608,6.738825,3.502100,7.391370,8.185802,0.899346
min,101.00000,22.000000,1.000000,12.000000,68.000000,2.000000
25%,105.75000,28.250000,3.000000,20.000000,76.000000,3.000000
50%,110.50000,32.500000,5.000000,24.000000,80.000000,4.000000
75%,115.25000,38.750000,8.000000,29.000000,88.000000,5.000000
max,120.00000,45.000000,12.000000,40.000000,95.000000,5.000000




### Section B: Cleaning & Missing Value Handling**

### **4️⃣ Identify which 3 columns have the highest number of missing values.**

In [8]:
missing_values = df_lab.isnull().sum()
top_3_missing = missing_values.nlargest(3)
print(top_3_missing)

ExperienceYears    3
TrainingHours      3
SkillScore         3
dtype: int64

5️⃣ Fill missing values in:
Age → with mean
Department → with mode
TrainingHours → with median

In [9]:
df_lab['Age'].fillna(df_lab['Age'].mean(), inplace=True)
df_lab['Department'].fillna(df_lab['Department'].mode()[0], inplace=True)
df_lab['TrainingHours'].fillna(df_lab['TrainingHours'].median(), inplace=True)
df_lab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         20 non-null     int64
 1   Age                20 non-null     float64
 2   Department         20 non-null     object
 3   ExperienceYears    17 non-null     float64
 4   TrainingHours      20 non-null     float64
 5   SkillScore         17 non-null     float64
 6   PerformanceRating  17 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.2+ KB

/tmp/ipykernel_1004/892192010.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_lab['Age'].fillna(df_lab['Age'].mean(), inplace=True)
/tmp/ipykernel_1004/892192010.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_lab['Department'].fillna(df_lab['Department'].mode()[0], inplace=True)
/tmp/ipykernel_1004/892192010.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_lab['TrainingHours'].fillna(df_lab['TrainingHours'].median(), inplace=True)

6️⃣ Remove rows where both SkillScore AND PerformanceRating are missing.

In [10]:
df_lab.dropna(subset=['SkillScore', 'PerformanceRating'], how='all', inplace=True)
df_lab.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeID         19 non-null     int64
 1   Age                19 non-null     float64
 2   Department         19 non-null     object
 3   ExperienceYears    17 non-null     float64
 4   TrainingHours      19 non-null     float64
 5   SkillScore         17 non-null     float64
 6   PerformanceRating  17 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.2+ KB

Section C: Column Operations**
7️⃣ Create a new column: TrainingEfficiency = SkillScore / TrainingHours.

In [12]:
df_lab['TrainingEfficiency'] = df_lab['SkillScore'] / df_lab['TrainingHours']
df_lab.head()

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating,TrainingEfficiency
0,101,25.0,IT,1.0,15.0,70.0,3.0,4.666667
1,102,28.0,HR,3.0,20.0,76.0,4.0,3.800000
2,103,32.0,Finance,5.0,24.0,80.0,4.0,3.333333
3,104,45.0,IT,10.0,40.0,90.0,5.0,2.250000
5,106,38.0,Finance,7.0,35.0,85.0,4.0,2.428571

8️⃣ Create another column: Category
Rules:

If PerformanceRating ≥ 4 → “High”
Else → “Low

In [15]:
df_lab['Category'] = df_lab['PerformanceRating'].apply(lambda x: 'High' if x >= 4 else 'Low')
df_lab.head()

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating,TrainingEfficiency,Category
0,101,25.0,IT,1.0,15.0,70.0,3.0,4.666667,Low
1,102,28.0,HR,3.0,20.0,76.0,4.0,3.800000,High
2,103,32.0,Finance,5.0,24.0,80.0,4.0,3.333333,High
3,104,45.0,IT,10.0,40.0,90.0,5.0,2.250000,High
5,106,38.0,Finance,7.0,35.0,85.0,4.0,2.428571,High

Section D: Filtering & Sorting**
9️⃣ Filter employees who:
Work in IT
Have SkillScore > 85
Have ExperienceYears ≥ 5

In [21]:
df_lab = df_lab[
    (df_lab['Department'] == 'IT') &
    (df_lab['SkillScore'] > 85) &
    (df_lab['ExperienceYears'] >= 5)
]
display(df_lab)

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating,TrainingEfficiency,Category
3,104,45.000000,IT,10.0,40.0,90.0,5.0,2.250000,High
6,107,33.333333,IT,9.0,18.0,88.0,5.0,4.888889,High
16,117,44.000000,IT,8.0,24.0,91.0,5.0,3.791667,High

🔟 Sort the dataset by ExperienceYears (descending) and SkillScore (ascending).

In [22]:
df_lab= df_lab.sort_values(by=['ExperienceYears', 'SkillScore'], ascending=[False, True])
display(df_lab.head())

,EmployeeID,Age,Department,ExperienceYears,TrainingHours,SkillScore,PerformanceRating,TrainingEfficiency,Category
3,104,45.000000,IT,10.0,40.0,90.0,5.0,2.250000,High
6,107,33.333333,IT,9.0,18.0,88.0,5.0,4.888889,High
16,117,44.000000,IT,8.0,24.0,91.0,5.0,3.791667,High

Section E: Grouping & Aggregation**
1️⃣1️⃣ Compute the average:
SkillScore by Department
PerformanceRating by Department

In [25]:
df_lab= df_lab.groupby('Department')[['SkillScore', 'PerformanceRating']].mean()
display(df_lab)

            SkillScore  PerformanceRating
Department
IT           89.666667                5.0

Section F: Final Step**
Save the cleaned dataset as Employee_Cleaned.csv.

In [26]:
df_lab.to_csv('Employee_Cleaned.csv', index=False)
print('Dataset saved as Employee_Cleaned.csv')

Dataset saved as Employee_Cleaned.csv